### ISSUE TITLE
License switch to LGPL

### ISSUE THREAD

**Issue by Immortalin** [thedarkcolour/KotlinForForge#5]
MC Forge uses LGPL, can this be switched to match it?

**Comment by thedarkcolour** [comment]
Why?

**Comment by thedarkcolour** [comment]
I'm just going to leave it as the more liberal license

**Comment by klikli-dev** [comment]
@thedarkcolour if I may chime in, I would like to bring this to your attention once more and answer why this may be desirable for some users - and possibly for you.

GPLv3 is a very restrictive copyleft license, in essence it means that every mod using your library **has to** use the GPLv3 license as well, they cannot choose a more permissive license. When distributing their mod they need to release the source code. This is known to some as 'infection', although I don't agree with the inherent judgement in that wording.

In contrast, the LGPL (of any version) used by Forge allows mods to choose their own license, and only (oversimplified) forks of kotlin-for-forge need to keep the LGPL.

This comes down to what your goals are: should all your users license their code under GPLv3 and release their source code? Then you should keep this license.

Should users be free in their choice for their mods , but modifications of your code should release the source? Then LGPL is the better choice.

Personally, in order to allow as many people as possible to use this library, without restrictions to their licensing choices, the LPGL seems like a better choice.

If I wanted to start using it, for example, I would have to re-license my mods as they are currently available under more permissive licenses. 

Hope I could shed some light on this! Let me know if you have further licensing questions :)

**Comment by klikli-dev** [comment]
@Immortalin you might be interested in #19 - the license was just updated to LGPL :)
